CREATE TABLE AFK (userID INTEGER, Since INTEGER, Reason TEXT);
CREATE TABLE Level (userID INTEGER PRIMARY KEY, XP Integer);
CREATE TABLE Moderation(warnID BINARY(16) PRIMARY KEY, userID INTEGER, modID INTEGER, reason TEXT);
CREATE TABLE TICKETS (userID INTEGER PRIMARY KEY, channelID INTEGER);