CREATE TABLE IF NOT EXISTS AFK (userID INTEGER, Since INTEGER, Reason TEXT);
CREATE TABLE IF NOT EXISTS Level (userID INTEGER PRIMARY KEY, XP Integer);
CREATE TABLE IF NOT EXISTS Moderation(warnID BINARY(16) PRIMARY KEY, userID INTEGER, modID INTEGER, reason TEXT);
CREATE TABLE IF NOT EXISTS TICKETS (userID INTEGER PRIMARY KEY, channelID INTEGER);
CREATE TABLE IF NOT EXISTS Config (logID INTEGER);
INSERT INTO Config VALUES (0);